### ISSUE TITLE
[low] All WAI Translations page - translations of "Standards/Guidelines" and "Video Subtitles"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-translations#157]
[All WAI Translations page](https://www.w3.org/WAI/translations/) has categories:
* Standards/Guidelines
* Video Subtitles

e.g., https://www.w3.org/WAI/translations/#italiano-italian

I'm thinking it would be good to provide those in the language of the listing.

The translation page is from: https://github.com/w3c/wai-website/blob/master/translations.md

The file of UI terms translated is here: https://github.com/w3c/wai-website-data/blob/master/translations.yml

That currently doesn't include either. _(Standards/<wbr>Guidelines is in https://github.com/w3c/wai-website-data/blob/master/navigation.yml ; however, we do not want to pull from that for this!)_

We could add "Standards/Guidelines" and "Video Subtitles" to https://github.com/w3c/wai-website-data/blob/master/translations.yml
or perhaps better to have them somewhere else?

**Comment by remibetin** [comment]
"Standards/Guidelines" & "Video Subtitles" are inserted in "All WAI Translations" page using an include that makes them translatable.

The best step forward is indeed to add them in https://github.com/w3c/wai-website-data/blob/master/translations.yml. When translations will be added for these terms, they will be used in "All WAI Translations" page.

For consistency, I recommend using this file rather than having them somewhere else.

**Comment by shawna-slh** [comment]
@remibetin O. is passing on this, so you can take it on whenever higher priorities are done.

**Comment by remibetin** [comment]
@shawna-slh Done and ready to publish here: https://github.com/w3c/wai-website-data/pull/120
