### ISSUE TITLE
Mock-up updates

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#18]
Hiya @yatil Here are things for us to discuss on Tuesday.

In "controls" banner at top:
- [x] Delete "Change Text Size or Colors" (I'll open a separate issue on this to get more input before we make a decision for the real site; for the mock up now, it'd be good not to have it.)
- [x] Separate languages with square W3C-blue bullets
- [x] Include non-European scripts in the lists of languages (e.g., [i18n](https://www.w3.org/International/articlelist#site-navigation))

For the box under secondary nav:
- [x] Indicate English is original: "English (original)" and make it always bold
- [x] Margins/padding so same left margin and text size same as nav box above
- [x] Use square W3C-blue bullets
- [x] add separator line then: "Other Resources in XYZlanguage"
- [x] add separator line then: "[language icon] Translating WAI Resources"

**Lower priority:**
- [ ] Provide examples with different number of languages:
* 5 languages (which will be common number for a quite a while I think)
* 15 languages (common max for most pages)
* 25 languages (likely max for all pages)
- [x] translate the main navigation on the French mockup page
- [x] in site footer after "Resources for Roles", add "[language icon] Translations"
- [ ] home page
  - [ ] @@...

**Comment by yatil** [comment]
I’m not really convinced using attention-grabbing red color with something that is not really the most important function of the website or an error. In 90% of instances, people will be on the page they want to be (redirected to the page in their preferred language or chose to change language). Changing language is a pure utility function and it should not get highlighted treatment vs. other page elements that are much more important for everyone else. That's why I would be cautious to use the navigation layout (margins/paddings) for the translations on the left. Translations should be muted, smaller and unobtrusive.
