### ISSUE TITLE
[Polish] Essential Components of Web Accessibility

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#181]
I would like to  translate into [language]  the following resource:

- Page URL: [https://www.w3.org/WAI/fundamentals/components/](https://www.w3.org/WAI/fundamentals/components/)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
@zwiastunsw Thanks for volunteering to translate this resource. I need to apply some minor updates to the resource before you can start your translation.

Feel free to ping me if you do not hear from me by March 6.

**Comment by remibetin** [comment]
@zwiastunsw This resource is now ready for translation! You can now translate the text of this resource located at:
- https://github.com/w3c/wai-components/edit/master/content/index.md
- https://github.com/w3c/wai-components/blob/master/content/wai-components-example.md

Regarding the images though, I will get back to you by next week with specific instructions.

Thanks again!

**Comment by remibetin** [comment]
Hi @zwiastunsw,

Thank you for your patience while I was preparing this resource for translation.

I am finally back with some news and the remaining instructions:
- Since your Pull Request, I have updated the resource. See https://github.com/w3c/wai-components/commits/master/content/index.md & https://github.com/w3c/wai-components/commits/master/content/wai-components-example.md
- Thank you for your SVG propositions. Unfortunately, they differ from the original versions. I have adapted and added the SVG versions prepared by @code-elegant some years ago. These are now the source files to be used as the starting point for translations. I have published a dedicated guide to follow: https://www.w3.org/WAI/about/translating/guides/images/

Here are the next steps in a nutshell:
- [ ] Update the draft translation with the latest updates from the original version.
- [ ] Translate the images according to the new guide: https://www.w3.org/WAI/about/translating/guides/images/
- [ ] Add a translation of "Long description of image" in https://github.com/w3c/wai-website-data/blob/master/translations.yml (see the end of the file)

Let me know if you have any question.

Thanks!

**Comment by remibetin** [comment]
QA done: ✅

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @zwiastunsw!

See https://www.w3.org/WAI/fundamentals/components/pl & https://www.w3.org/WAI/fundamentals/components/examples/pl
