### ISSUE TITLE
Top list is site-wide, page list is elsewhere

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#19]
Note: We are translating the "chrome" - header, footer, and all navigation when the resulting page is in that language, including some of the home page. (So it's a bit more than a page-only translation, yet not the full website.)

Proposal:
1. **top list is site-wide** &mdash; The full list of languages is always at the very top right. Clicking on a language there leads to a list of all pages available in that language.
2. **page list is elsewhere** &mdash;  Around the h1 or breadcrumb is "Select Language" toggle that displays languages of that page only. Clicking on a language there changes the language of that page.

See pros, cons, etc. at https://www.w3.org/wiki/WAI_Translations#21_November_Issues

Please comment below **on this overall proposal**.<br>Any comments _specifically on the location or wording of the page-list (2 above)_, please put in [Issue 20](https://github.com/w3c/wai-translations/issues/20) instead of here.

**Comment by r12a** [comment]
This all sounds too complicated to me.  For a start, if there are two lists of language on a page, i'm not sure i'll be able to remember which is which, and the current mockup doesn't appear to help me realise the function of the top list.

Secondly, i'm not particularly convinced that there's much utility in the proposition that, if you couldn't easily read the information you were looking for because it's not translated, you'd be happy to go off and read something completely different, instead.  Particularly if this is a translation such as Turkish, or Ewe, where the number of translated pages might be quite small.

And anyway, i think i'd prefer a general link, such as the A-文 icon, to take me to a separate page that lists content available languages (a kind of landing page), rather than provide another list of languages. (And by the way, i think such a list should be a complete site map, rather than just a list of the, say, 2 pages available in Ewe, and allow you to switch to another language, such as French, in place to see what's available in that language.  

Thirdly, i'm not sure of the utility of translating the boilerplate text if the body isn't translated – on the one hand, people may think this is a badly localised site, on the other, perhaps you're trying to encourage people to supply the missing text(?).  But if you did do that, i don't think you'd need two different sets of links to translated pages.  Essentially, i think that in such a scenario the top set of links (if i have correctly understood) would effectively change the language mode of the site. If the mode is currently English and you switch to, say, French, then presumably the language of the current page would switch also and if the body text is available in French it would appear.  Then following links thereafter would bring in all the french wherever it's available.   What's the utility of a second set of language links that only changes the language for that particular page?  

Btw, if you do translate the boilerplate, you'll need to pay careful attention to the untranslated arabic, hebrew, etc pages, since the directionality and display orientation of boilerplate and body text will be different.

**Comment by slhenry** [comment]
After discussions, this approach rejected.
