### ISSUE TITLE
Translations Priorities

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#31]
Draft **[Priorities for Translating WAI Resources](https://github.com/w3c/wai-about-wai/blob/translating-new2019/_about/translating.md#priorities-for-translating-wai-resources-priorities)** are available for input.

Please see the note and additional information in the **[Translation Priorities](https://www.w3.org/wiki/WAI_Translations#Translation_Priorities)** section of the WAI Translations wiki page.

We'll discuss priorities in the 11 January EOWG telecon. Feel free to add rationale for different priorities here now, or after the meeting.

**Comment by cousquer** [comment]
Hi @slhenry 👋 ,
I will start today to systematically translate all documents into French in accordance with the order of priorities you have defined.
I will give you feedbacks on the translation process, if you wish.
Let's go. andiamo...

**Comment by yatil** [comment]
@cousquer We’re not ready yet, and we have other French translators to coordinate with. We need to prepare the documents and also do quite some technical implementation. Thanks for your enthusiasm, but please wait until we have a process in place and can give you green light, otherwise you might do duplicate work or work that cannot be used or has to be altered before it can be used. :-)

**Comment by cousquer** [comment]
Ok, no problem. Apologies and thanks for the warning @yatil. 😄 I thought that "This resource is ready for translation." in the README was a green light...

**Comment by slhenry** [comment]
SLH to do: consider section headings (e.g., ee comments)

**Comment by slhenry** [comment]
done https://w3c.github.io/wai-about-wai/about/translating/#priorities
