### ISSUE TITLE
location for list of translations on a page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#5]
UPDATE: Straw proposal changed to "top, right (in panel that starts with "Skip to Content", right aligned)" per [below](https://github.com/w3c/wai-translations/issues/5#issuecomment-433522882)

Proposed: <s>left column after section navigation, as in [mock-up](https://w3c.github.io/wai-translation-playground/people-use-web/)</s>

Before commenting on other options, please read [details on **Location options** in wiki](https://www.w3.org/wiki/WAI_Translations#Location).

**Comment by notabene** [comment]
I don't feel strongly about it and note that this is where Wikipedia does it, so I'm all for it.
(Just as a fyi: they also use a pictogram when viewed on mobile to push the info to the top of the page, but it's optional and may come up only when we have a substantial amount of translations I guess.)

**Comment by yatil** [comment]
Support for this, but only with a reworked mobile menu for discoverability.

**Comment by slhenry** [comment]
I analyzed several more [examples](https://www.w3.org/wiki/WAI_Translations#Examples_.28not_sayin.27_good_or_bad.29). Almost **all have the translations at the top right** (whether an always visible list, or a selector to get a list).

And I thought about Eric's comments on another issue [_emphasis mine_]
> I think showing the whole navigation with gaps of language support _**shows our commitment to translation**_. When I get to a website that has a nice little German corner with a fraction of the information, I don’t feel included and I know there is _**no commitment to making all content available**_. (comment shared with permission)<br>
> having language “ghettos” means that people don’t see the breadth of our content, it also means we don’t _**show a commitment to translations to the user**_. ([e-mail](https://lists.w3.org/Archives/Public/public-eo-archive/2018OctDec/0015.html))

I added more considerations to the wiki page, including:
> If the list of translations is very visible and easy to use, they will be more prominent in the visual design. On the one hand, that may be cluttering for users who only want the English. On the other hand, it shows WAI's support for translations, so it may be worth it.

And changed the straw proposal:
> [Location of the list of languages](https://www.w3.org/wiki/WAI_Translations#Location): top, right (in panel that starts with "Skip to Content", right aligned)

It's still open to more input!

**Comment by slhenry** [comment]
user experience fyi: Even when *told* that the language was under the H1 on https://webdesign.tutsplus.com/articles/want-to-learn-web-design-basics-start-here--cms-27341
3 out of 3 people had trouble finding it visually ([30 Oct](https://www.w3.org/2018/10/30-eo-minutes.html))

**Comment by slhenry** [comment]
Decided:
* primary location: top, right (in panel that starts with "Skip to Content", right aligned)
* secondary location (in case people miss it at the top): left column after secondary navigation

**Comment by brewerj** [comment]
I've looked at the mock-ups multiple times, and read the comments above and on the linked page about positioning of the available languages. 

I believe that the positioning of available languages way at the top of the Web page impairs discovery of resource-specific translations because there is no clear association with the title of the document for which the translations are provided. The list of languages at the top of the page appears, because of proximity, to be a list of translations for the site as a whole, not for this specific document. 

The list of reasons for positioning the available languages at the top do not seem convincing, and actually reinforce my concern that positioning translations at the top won't improve discoverability but rather will invite confusion. Responding to the most relevant points from <https://www.w3.org/wiki/WAI_Translations#Location>
1) "this is the most common location, in almost all examples, thus most users will look there for it" -- I think that your examples show the opposite. Even as noted at the top of the list of examples, these examples are mostly showing site-wide required languages for international agencies, not resource-specific languages. Using the top-most positioning to list available translations only for a specific resource would thus be more likely to create confusion for users who are familiar with language availability listings on international websites that provide site-wide language translations, because they'll misinterpret these as site-wide languages, and miss them as resource-specific languages.  
"that this is where most people would look for it" -- I think most people would look for it after confirming that they're on the page for the resource they're looking for, e.g., after the document title.
4) "too cluttering for all readers, most of whom don't want a different language than they get. (we're estimating that 90% of readers will get the language that they want from language negotiation)" -- Then make the list of translations expandable and collapsible, so that people can hide the list if they're not interested. W3C is an international website, and the more that the majority of our website users are aware of multiple translations of our materials, the more they may help bring those to other people's attention, and maybe help us get more translations. This argument sounds too much to me like the "handicapped don't come here anyway" argument that shop owners sometimes use to push back on requests for ramps. Much of the world's population is bilingual, not monolingual, and not first-language English speakers. There is a broader interest in translations of our materials -- particularly if we emphasize that more in our outreach. 
- Also "we're estimating that 90% of readers will get the language that they want from language negotiation" -- while that may be true, a lot of what we do with WAI outreach is to be a multiplier -- to try to get people the resources that they can use to spread the word to other communities, since we can't reach everyone directly. Ensuring transparency of the translations that we have can help people think more about spreading the word for what we've got, and helping us fill in the gaps for what we don't have yet. Many people working on web accessibility have connections with multiple different language communities, and see the translations list as valuable info, not clutter, (particularly if it can be suppressed if needed). Proximity of the translations list can help people more naturally understand what we're showing them.

I strongly think that the positioning question needs more consideration before the new translation interface is finalized. Minimally, if for whatever other reasons the translations list needs to be kept in the top-most position, find a brief way to indicate that the list is relevant for this particular resource. I'd be happy to join a discussion on the positioning if needed. 
- Judy

**Comment by brewerj** [comment]
Responding to an off-github request for me to make clearer suggestions of alternatives to the top-most position for the list of available translations: 

1. One alternative position would be to provide the list of available translations right under the name of the document (H1). This was listed as option #4 https://www.w3.org/wiki/WAI_Translations#Examples and dismissed as too cluttering, and unnecessary because most people would get what they want by language negotiation. I think that (a) visibility of the translations list would be a feature, not a bug, for reasons cited above; (b) and even where people get what they need by language negotiation, it is still valuable for people to be able to see what other languages a resource may be available in; and (c) if indeed it is too cluttering to be able to see the different translations available, these could be made available through a snow/hide option.

2. Another alternative would be put the list in the upper right (for left to right languages) as it is on the internationalization resource pages https://www.w3.org/International/articlelist . This also has the advantage of being expandable if we get lucky with a lot of translations, without filling up too much of the space right under the H1.

**Comment by slhenry** [comment]
Closing this issue as the proposal has changed.

(Feel free to reply to above without re-opening the issue if you want to get responses recorded here.)

**[21 Nov New Proposal and Options](https://www.w3.org/wiki/WAI_Translations#21_November_Issues)**
