### ISSUE TITLE
labeling of link to show list of translations on a page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#7]
The [mock-up](https://w3c.github.io/wai-translation-playground/people-use-web/) currently has "Select Language"/"Hide Language Selector"

**Please see a [list of several different Labelling options](https://github.com/w3c/wai-translations/wiki/WAI-Translations-Overall-Approach,-Issues,-etc#labelling-options) in wiki page.**

Please comment on why certain options might work better or not as well for the target audience: people who want or need a language other than English.

**Comment by r12a** [comment]
In my opinion, using a pulldown to select languages should be avoided whenever possible, and is only really needed when you have quite a large number of alternatives to choose from.  (See https://www.w3.org/International/questions/qa-navigation-select#proscons.)  If you use a pulldown control, you really can't use text for the label, since it will be difficult for someone to find if they don't speak the language that the label is written in.  However it is also difficult to find a graphic alternative that is readily recognisable.

In the mockup, the label for the pulldown is in English even though the page is in French. Is that intentional? I think, if you are going to have text, it should be in French.

![screen shot 2018-10-18 at 08 17 07](https://user-images.githubusercontent.com/4839211/47139403-a8563100-d2b3-11e8-92aa-839eac42cc20.png)

I strongly recommend using a list of links, rather than a pulldown control. The link text of each should be the name of the language of the target page, written in that language.

**Comment by yatil** [comment]
@r12a 

> I strongly recommend using a list of links, rather than a pulldown control. 

We are not using a pulldown, it is more an expand/collapse :-) The reason why the button is English on the French version is that if someone gets to the translated page by accident, they would probably find it easier to find the option to change the language in English than in French.

> If you use a pulldown control, you really can't use text for the label, since it will be difficult for someone to find if they don't speak the language that the label is written in. However it is also difficult to find a graphic alternative that is readily recognisable.

That’s why we use an icon with the text “show languages”.

> The link text of each should be the name of the language of the target page, written in that language.

That’s what we do.

**Comment by slhenry** [comment]
trying different approach, so this is not currently an open issue
